# Env mode (local, production, development)
env: local

# Path to PostgreSQL db
conn_str: 'postgres://postgres:password@localhost/dbname?sslmode=verify-full'

# HTTP server config
server_config:
  address: 'localhost:3000'
  # Timeout for response reading and writing
  req_timeout: 4s
  # Lifetime of connection with client
  idle_timeout: 60s
